### ISSUE TITLE
Auto create task by clicking on start

### ISSUE THREAD

**Issue by androettop** [Angele91/tutto#1]
If you have selected a task and then want to create a new one you need to click first on `Create "task"` and then you can hit start.

I think avoiding that extra step would improve the user experience.

![image](https://user-images.githubusercontent.com/17651502/213488886-e3297fe2-e530-4036-8b1a-0780de17d15b.png)

**Comment by Angele91** [comment]
Thank you for the recommendation! 
I've just included this in the lastest version.
https://github.com/Angele91/tutto/commit/90b38882b890dab14219ac853399572a9ae80f41
